### ISSUE TITLE
dropout 2次是哪里进行的？

### ISSUE THREAD

**Issue by jifei** [enze5088/WenTianSearch#2]
请教一下，dropout 2次通过一个batch里构造重复样本，这个逻辑在哪里呀？

**Comment by nursery42** [comment]
直接文本输入bert就是了，bert本身内部结构中自带dropout,一个样本输入一次的时候，他输出的向量就已经经过了dropout。当把相同一个样本重复输入两次的时候，这个样本输出的向量因为dropout的原因是会略有不同的。相当于经过了两次dropout。这一点可以参考看看SimCSE原文。

**Comment by jifei** [comment]
就是同一个样本，重复输入两次的逻辑没有找到.

**Comment by nursery42** [comment]
> 就是同一个样本，重复输入两次的逻辑没有找到.

这个是SimCSE原文做无监督的时候做的，我们是用query<-->doc，并不需要一个样本重复输入两次。
