### ISSUE TITLE
对z1z2做normalize的目的

### ISSUE THREAD

**Issue by vmomet** [enze5088/WenTianSearch#3]
您好，

请教一下，代码中对z1和z2向量做normalize有什么作用？
https://github.com/enze5088/WenTianSearch/blob/b722f54a85b579229268f42453ef682ae321ed5e/simcse/models.py#L202

**Comment by nursery42** [comment]
赛题里用的是欧氏距离，余弦相似度L2归一化之后和欧氏距离等价。

**Comment by vmomet** [comment]
感谢指点，学习了。

**Comment by ManagerYu10** [comment]
补一个图解释等价性。
在归一化之后，求余弦相似度==求角θ==求弧长==求弦长==求欧式距离
![image](https://user-images.githubusercontent.com/30391848/161420752-72e39de2-085f-4c6b-9d81-35e18ea4c818.png)
