### ISSUE TITLE
greater_is_better为何设为True？

### ISSUE THREAD

**Issue by ManagerYu10** [enze5088/WenTianSearch#4]
看到greater_is_better设置为True，会导致存储的checkpoint是metric最大的的
而metric默认是infoNCE loss，那么是不是会导致存下来的模型不是最优的呢？
```
    greater_is_better: Optional[bool] = field(
        default=True, metadata={"help": "Whether the `metric_for_best_model` should be maximized or not."}
    )
```
https://github.com/enze5088/WenTianSearch/blob/b722f54a85b579229268f42453ef682ae321ed5e/2.train.py#L229

**Comment by nursery42** [comment]
评估的metric我写的是acc，所以应该是越大越好。
